"""Added catalog brand table

Revision ID: 743114258b86
Revises: 
Create Date: 2023-08-07 16:18:48.937061

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '743114258b86'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'catalog',
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=False),
        sa.Column('price', sa.Numeric(), nullable=False),
        sa.Column('picture_file_name', sa.String(length=255), nullable=False),
        sa.Column('picture_uri', sa.String(length=255), nullable=False),
        sa.Column('catalog_type_id', sa.Integer(), nullable=False),
        sa.Column('catalog_brand_id', sa.Integer(), nullable=False),
        sa.Column('available_stock', sa.Integer(), nullable=False),
        sa.Column('restock_threshold', sa.Integer(), nullable=False),
        sa.Column('max_stock_threshold', sa.Integer(), nullable=False),
        sa.Column('on_reorder', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'catalog_brand',
        sa.Column('brand', sa.String(length=255), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalog_brand')
    op.drop_table('catalog')
    # ### end Alembic commands ###
