"""Added catalog type table

Revision ID: 96cd6e0184bc
Revises: 743114258b86
Create Date: 2023-08-07 16:43:41.255292

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '96cd6e0184bc'
down_revision: Union[str, None] = '743114258b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'catalog_type',
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalog_type')
    # ### end Alembic commands ###
