"""Initial migration.

Revision ID: d77184bd560d
Revises: 
Create Date: 2023-08-05 09:40:49.552943

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd77184bd560d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'catalog',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('price', sa.DECIMAL(), nullable=True),
        sa.Column('picture_file_name', sa.String(length=255), nullable=True),
        sa.Column('picture_uri', sa.String(length=255), nullable=True),
        sa.Column('catalog_type_id', sa.Integer(), nullable=True),
        sa.Column('catalog_brand_id', sa.Integer(), nullable=True),
        sa.Column('available_stock', sa.Integer(), nullable=True),
        sa.Column('restock_threshold', sa.Integer(), nullable=True),
        sa.Column('max_stock_threshold', sa.Integer(), nullable=True),
        sa.Column('on_reorder', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalog')
    # ### end Alembic commands ###
